/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CycloneRouteImport } from './routes/cyclone'
import { Route as CyclonePlanRouteImport } from './routes/cyclone-plan'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as RankRouteImport } from './routes/rank'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TotalsRouteImport } from './routes/totals'
import { Route as ExercisesIdRouteImport } from './routes/exercises.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CycloneRoute = CycloneRouteImport.update({
  id: '/cyclone',
  path: '/cyclone',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclonePlanRoute = CyclonePlanRouteImport.update({
  id: '/cyclone-plan',
  path: '/cyclone-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TotalsRoute = TotalsRouteImport.update({
  id: '/totals',
  path: '/totals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExercisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cyclone': typeof CycloneRoute
  '/cyclone-plan': typeof CyclonePlanRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/flow': typeof FlowRoute
  '/matrix': typeof MatrixRoute
  '/rank': typeof RankRoute
  '/settings': typeof SettingsRoute
  '/totals': typeof TotalsRoute
  '/exercises/$id': typeof ExercisesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cyclone': typeof CycloneRoute
  '/cyclone-plan': typeof CyclonePlanRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/flow': typeof FlowRoute
  '/matrix': typeof MatrixRoute
  '/rank': typeof RankRoute
  '/settings': typeof SettingsRoute
  '/totals': typeof TotalsRoute
  '/exercises/$id': typeof ExercisesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cyclone': typeof CycloneRoute
  '/cyclone-plan': typeof CyclonePlanRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/flow': typeof FlowRoute
  '/matrix': typeof MatrixRoute
  '/rank': typeof RankRoute
  '/settings': typeof SettingsRoute
  '/totals': typeof TotalsRoute
  '/exercises/$id': typeof ExercisesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cyclone'
    | '/cyclone-plan'
    | '/exercises'
    | '/flow'
    | '/matrix'
    | '/rank'
    | '/settings'
    | '/totals'
    | '/exercises/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cyclone'
    | '/cyclone-plan'
    | '/exercises'
    | '/flow'
    | '/matrix'
    | '/rank'
    | '/settings'
    | '/totals'
    | '/exercises/$id'
  id:
    | '__root__'
    | '/'
    | '/cyclone'
    | '/cyclone-plan'
    | '/exercises'
    | '/flow'
    | '/matrix'
    | '/rank'
    | '/settings'
    | '/totals'
    | '/exercises/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CycloneRoute: typeof CycloneRoute
  CyclonePlanRoute: typeof CyclonePlanRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  FlowRoute: typeof FlowRoute
  MatrixRoute: typeof MatrixRoute
  RankRoute: typeof RankRoute
  SettingsRoute: typeof SettingsRoute
  TotalsRoute: typeof TotalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyclone': {
      id: '/cyclone'
      path: '/cyclone'
      fullPath: '/cyclone'
      preLoaderRoute: typeof CycloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyclone-plan': {
      id: '/cyclone-plan'
      path: '/cyclone-plan'
      fullPath: '/cyclone-plan'
      preLoaderRoute: typeof CyclonePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totals': {
      id: '/totals'
      path: '/totals'
      fullPath: '/totals'
      preLoaderRoute: typeof TotalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
  }
}

interface ExercisesRouteChildren {
  ExercisesIdRoute: typeof ExercisesIdRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesIdRoute: ExercisesIdRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CycloneRoute: CycloneRoute,
  CyclonePlanRoute: CyclonePlanRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  FlowRoute: FlowRoute,
  MatrixRoute: MatrixRoute,
  RankRoute: RankRoute,
  SettingsRoute: SettingsRoute,
  TotalsRoute: TotalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
